networks:
  ws-network:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    networks:
      - ws-network
    restart: unless-stopped

  wss:
    build:
      context: .
    image: websocket-app:latest
    environment:
      - WSS_PORT=8081
      - METRICS_PORT=9000
      - ENVIRONMENT=local
      - REDIS_URI=redis://redis:6379
    ports:
      - "8081:8081"
      - "9000:9000"
    networks:
      - ws-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - ws-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - ws-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./metrics/grafana/provisioning:/etc/grafana/provisioning
      - ./metrics/grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
